#ifndef READER_COMMANDS_H
#define READER_COMMANDS_H

//COMMAND ADDRESS
#define READER_ADR_BROADCAST 0xFF

//COMMAND ID
#define READER_CMD_OBTAIN_INFO 0x21
#define READER_CMD_CHANGE_MODE 0x76
#define READER_CMD_OBTAIN_TEMP 0x92

// COMMAND ARGUMENT
#define READER_ARG_ANSWER_MODE 0x0

// RESPONSE COMMAND
#define READER_RCMD_RTI 0xee

// RESPONSE STATUS
#define READER_RSTATUS_RTI_TAG_FOUND 0x0
#define READER_RSTATUS_RTI_NO_TAG_FOUND 0x28

#endif