#ifndef READER_COMMANDS_H
#define READER_COMMANDS_H

#define READER_ADR_BROADCAST 0xFF

#define READER_CMD_OBTAIN_INFO 0x21
#define READER_CMD_CHANGE_MODE 0x76
#define READER_CMD_OBTAIN_TEMP 0x92

#define READER_RCMD_RTI 0xee

#define READER_ARG_ANSWER_MODE 0x0
#endif